title: "TESTING MODE"
description: "PhD in Computational Chemistry"
url: "https://dilawars9.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

author:
  name: "Dilawar Singh Sisodiya"
  bio: "PhD in Theoretical Chemistry."
  location: "Goa, India"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Dilawars9"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
