title: "Dilawar Singh Sisodiya"
description: "PhD in Computational Chemistry | BITS Pilani"
url: "https://dilawars9.github.io"
baseurl: ""

# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Author Details (Left Sidebar)
author:
  name: "Dilawar Singh Sisodiya"
  bio: "PhD in Theoretical Chemistry. Investigating reaction mechanisms and photochemistry."
  location: "Goa, India"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Dilawars9"
    - label: "Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=Oki-eAQAAAAJ"

# Navigation (Looks for _data/navigation.yml)
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
